az_storage_account_name: storageaccountname
az_container_name:       sapmediacontainer
az_sas_token:            <SAS_TOKEN>
az_blobs:
  - SAPCAR.EXE
  - IMDB_SERVER20_062_0-80002031.SAR
  - IMDB_CLIENT20_012_25-80002082.SAR