# The name of the file store which will hold the SBD lun/s
config_backstore_name: 'sbdhana'

# 
# For compliance with RFC 3720 (as much as is practical), the first part of the IQN will be set as:
# iqn.<current_year>-<current_month>.<naming_authority>:<meaningful_name>
# A good example of this would be iqn:2022-08.com.suse:local:hana.cluster.sbd
# This automation will compute the first part iqn, the naming authority and meaningful name can be defined below.
# By default, the the naming authority will be set to `local.hanasbd` and the meaningful name to 'hana_sbd'
config_server_iqn_name_authority: 'com.suse.hanasbd'
config_server_meaningful_name: 'hanadb'

# The clients will also require an iqn and a meaningful name.
# The iqn default is local.hana01 and local.hana02
# The default meaningful names are hanadb-01 and hanadb-02
config_client01_iqn_name_authority: 'com.suse.hana01'
config_client02_iqn_name_authority: 'com.suse.hana02'
config_client01_meaningful_name: 'hana-db-1'
config_client02_meaningful_name: 'hana-db-2'