---
# tasks sourced from
# https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/high-availability-guide-suse-pacemaker
- name: Enable required services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
  with_items:
    - iscsid
    - iscsi
    - sbd

# This loop ensures that each hana host has a unique iscsi initiator name.
# The initiator names are composed from client0x_iqn_name_authority & client0x_meaningful_name and added to the
# client_list.  They are then added to /etc/iscsi/initiatorname.iscsi in the order they appear in the client list
# to the hosts in the hana group in the inventory.
- name: Edit initiator
  ansible.builtin.lineinfile:
    path: /etc/iscsi/initiatorname.iscsi
    regexp: '^InitiatorName='
    line: 'InitiatorName={{ item }}'
  when: inventory_hostname in groups.hana[index]
  loop: "{{ client_list | flatten(levels=1) }}"
  loop_control:
    index_var: index
  notify:
    - Restart iscsi

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Scan iscsi disks
  ansible.builtin.command:
    cmd: "iscsiadm -m discovery --type=st --portal={{ hostvars[item]['ansible_default_ipv4']['address'] }}:3260"
    creates: "/etc/iscsi/nodes/{{ srv_iqn }}/{{ hostvars[item]['ansible_default_ipv4']['address'], 3260, 1 }}"
  loop: "{{ groups['iscsi'] }}"
  register: discovered_iscsi

- name: Login for iscsi
  ansible.builtin.command:
    cmd: "iscsiadm -m node -T {{ srv_iqn }} --login --portal={{ item.stdout | split(':') | first }}"
    creates: "/dev/disk/by-path/ip-{{ item.stdout | split(':') | first }}:3260-iscsi-{{ srv_iqn }}-lun-0"
  loop: "{{ discovered_iscsi.results | selectattr('changed') | list }}"
  register: login

- name: Set LUNs to automatic
  ansible.builtin.command:
    cmd: "iscsiadm -m node -p {{ item.item.stdout | split(':') | first }}:3260 -T {{ srv_iqn }} --op=update --name=node.startup --value=automatic"
  register: iscsiadm_result
  changed_when: iscsiadm_result.rc == 0
  loop: "{{ login.results | selectattr('changed') | list }}"
