name: 'Markdown'

on:
  push:
    branches:
    - "main"
  pull_request:

permissions:
  contents: read

jobs:
  markdown_lint:
    name: 'Markdown lint'
    runs-on: ubuntu-latest
    environment: production
    strategy:
      matrix:
        docfile: ['README.md', 'terraform/aws/README.md', 'terraform/azure/README.md', 'docs/playbooks/README.md']

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: markdownlint-cli
      uses: nosborn/github-action-markdown-cli@v3.1.0
      with:
        files: ${{ matrix.docfile }}
        config_file: .markdownlint.json

    - name: Spell-check Markdown files
      uses: streetsidesoftware/cspell-action@v2.2.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        incremental_files_only: false
        config: 'cspell.json'
        files: ${{ matrix.docfile }}